/**============================================================================
Name        : strategy.hpp
Created on  : 17.08.2026
Author      : Andrei Tokmakov
Version     : 1.0
Copyright   : Your copyright notice
Description : Trading strategy interface.
============================================================================**/

/*
    IStrategy represents a trading strategy.

    A strategy consumes MarketEvent objects generated by the market data
    processing pipeline and decides whether a trading action is required.

    Data Flow:

        MarketDataSource
                |
                v
        MarketDataMessageHandler
                |
                v
        MarketDataParser
                |
                v
        BookUpdate
                |
                v
        BookBuilder
                |
                v
        MarketEvent
                |
                v
        IMarketEventHandler
                |
                v
        IStrategy
                |
                v
        OrderManager
                |
                v
        ExecutionGateway

    The strategy does not know how market data is received or parsed.

    The strategy also does not communicate directly with an exchange.
    Orders are submitted through the execution layer.
*/

#ifndef FINANCETECHNOLOGYPROJECTS_STRATEGY_HPP
#define FINANCETECHNOLOGYPROJECTS_STRATEGY_HPP

#include "market_event.hpp"

namespace trading::strategy
{
    struct IStrategy
    {
        virtual ~IStrategy() = default;

        virtual void onMarketEvent(const market_data::MarketEvent& event) = 0;
    };
}

#endif //FINANCETECHNOLOGYPROJECTS_STRATEGY_HPP